name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.31
  path_provider: ^2.1.5
  path: ^1.9.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.5
  intl: ^0.19.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  permission_handler: ^11.4.0
  google_mlkit_face_detection: ^0.13.1
  wakelock_plus: ^1.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4


flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/mobilefacenet.tflite
    - assets/Subtract.png